# Generated by Django 4.1.4 on 2022-12-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("primeiro_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoria",
            name="descricao",
            field=models.TextField(blank=True, null=True),
        ),
    ]
