# Generated by Django 4.1.4 on 2022-12-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("primeiro_app", "0002_alter_categoria_descricao"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=200, verbose_name="Nome Completo"),
                ),
                ("data_nasc", models.DateField()),
                ("cpf", models.IntegerField(verbose_name="CPF")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("telefone", models.IntegerField(verbose_name="Telefone")),
                (
                    "sexo",
                    models.CharField(
                        choices=[
                            ("M", "Masculino"),
                            ("F", "Feminino"),
                            ("N", "Não Declarar"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "estado_civil",
                    models.CharField(
                        choices=[
                            ("S", "Solteiro"),
                            ("C", "Casado"),
                            ("D", "Divorciado"),
                            ("v", "Viúv(o/a)"),
                        ],
                        max_length=1,
                    ),
                ),
            ],
        ),
    ]
