# Generated by Django 4.1.4 on 2022-12-20 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("primeiro_app", "0004_rename_cliente_usuario"),
    ]

    operations = [
        migrations.CreateModel(
            name="Endereco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cep", models.IntegerField(verbose_name="CEP")),
                ("rua", models.CharField(max_length=120, verbose_name="Rua")),
                ("numero", models.IntegerField(verbose_name="Numero")),
                ("complemento", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="autor",
            options={"verbose_name_plural": "Autores"},
        ),
        migrations.AlterModelOptions(
            name="livro",
            options={"verbose_name_plural": "Livros"},
        ),
        migrations.AlterField(
            model_name="usuario",
            name="cpf",
            field=models.CharField(max_length=120, verbose_name="CPF"),
        ),
        migrations.AddField(
            model_name="usuario",
            name="endereco",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="primeiro_app.endereco",
                verbose_name="Endereco",
            ),
        ),
    ]
