# Generated by Django 4.1.4 on 2022-12-20 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "primeiro_app",
            "0005_endereco_alter_autor_options_alter_livro_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="endereco",
            name="cep",
            field=models.CharField(max_length=120, verbose_name="CEP"),
        ),
    ]
